<a href="https://colab.research.google.com/github/JaganMurugan/Learning/blob/main/d2l_book.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x = torch.arange(12, dtype=torch.float32)

In [ ]:
x.numel()

12

In [ ]:
x.shape

torch.Size([12])

In [ ]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X = x.reshape(-1, 4)

In [ ]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.randn((2, 3, 4))

tensor([[[-0.4673, -1.1107, -1.8770,  1.0244],
         [ 0.4275, -0.9663,  0.8899,  1.6068],
         [ 0.3267, -0.7672, -0.8403, -0.5757]],

        [[ 0.3120, -0.2524, -1.2729, -1.4109],
         [-0.0041,  1.2126, -0.9615,  1.1353],
         [ 0.4328, -0.0590,  0.9931,  0.0376]]])

In [ ]:
X = torch.randn(3, 4)

In [ ]:
X

tensor([[ 1.3778,  0.0315, -0.5616, -0.5031],
        [ 0.9406,  1.2915,  0.2060, -0.9389],
        [-0.6941,  2.3882,  0.6741,  0.6631]])

In [ ]:
X[-1]

tensor([-0.6941,  2.3882,  0.6741,  0.6631])

In [ ]:
X[1:3]

tensor([[ 0.9406,  1.2915,  0.2060, -0.9389],
        [-0.6941,  2.3882,  0.6741,  0.6631]])

In [ ]:
import torch

In [ ]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [1]:
import torch

In [2]:
X = torch.arange(0, 5, 1)
X

tensor([0, 1, 2, 3, 4])

In [3]:
Y = torch.arange(1, 10, 2)

In [4]:
before = id(Y)
Y = Y + X
id(Y) == before

False