<a href="https://colab.research.google.com/github/JaganMurugan/Learning/blob/main/Torch_Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import torch

In [ ]:
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

In [ ]:
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

In [ ]:
labels_map = {
    0: "T-Shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle Boot",
}

rows, cols = 3, 3


In [ ]:
figure = plt.figure(figsize=(8, 8))
for i in range(1, rows*cols + 1):
  index = torch.randint(len(training_data), size=(1,)).item()
  img, label = training_data[index]
  figure.add_subplot(rows, cols, i)
  plt.title(labels_map[label])
  plt.axis("off")
  plt.imshow(img.squeeze(), cmap="grey")

plt.show()




In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dates = pd.date_range("20250726", periods=6)
dates

DatetimeIndex(['2025-07-26', '2025-07-27', '2025-07-28', '2025-07-29',
               '2025-07-30', '2025-07-31'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2025-07-26  0.133154 -1.440705  0.887715  0.614015
2025-07-27  0.875091 -0.541200 -0.721368 -1.084959
2025-07-28 -0.684352 -0.915786  0.790696 -0.563741
2025-07-29  0.235958 -0.009714 -0.353924 -1.007510
2025-07-30 -1.355920  0.898452 -0.341683 -0.627940
2025-07-31  0.661196 -0.641157 -0.115737 -0.744153

In [ ]:
np.array([3])

array([3])

In [ ]:
np.array([3]).shape

(1,)

In [ ]:
np.array([3]* 4)

array([3, 3, 3, 3])

In [ ]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20250726"),
    "C": pd.Series(1, index=list(range(4)), dtype="float32"),
    "D": np.array([3] * 4, dtype="float32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})
df2

A          B    C    D      E    F
0  1.0 2025-07-26  1.0  3.0   test  foo
1  1.0 2025-07-26  1.0  3.0  train  foo
2  1.0 2025-07-26  1.0  3.0   test  foo
3  1.0 2025-07-26  1.0  3.0  train  foo

In [ ]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D          float32
E         category
F           object
dtype: object

In [ ]:
df2.head()

A          B    C    D      E    F
0  1.0 2025-07-26  1.0  3.0   test  foo
1  1.0 2025-07-26  1.0  3.0  train  foo
2  1.0 2025-07-26  1.0  3.0   test  foo
3  1.0 2025-07-26  1.0  3.0  train  foo

In [ ]:
df2.tail()

A          B    C    D      E    F
0  1.0 2025-07-26  1.0  3.0   test  foo
1  1.0 2025-07-26  1.0  3.0  train  foo
2  1.0 2025-07-26  1.0  3.0   test  foo
3  1.0 2025-07-26  1.0  3.0  train  foo

In [ ]:
df2.tail(2)

A          B    C    D      E    F
2  1.0 2025-07-26  1.0  3.0   test  foo
3  1.0 2025-07-26  1.0  3.0  train  foo

In [ ]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [ ]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [ ]:
df2.to_numpy()

array([[1.0, Timestamp('2025-07-26 00:00:00'), 1.0, 3.0, 'test', 'foo'],
       [1.0, Timestamp('2025-07-26 00:00:00'), 1.0, 3.0, 'train', 'foo'],
       [1.0, Timestamp('2025-07-26 00:00:00'), 1.0, 3.0, 'test', 'foo'],
       [1.0, Timestamp('2025-07-26 00:00:00'), 1.0, 3.0, 'train', 'foo']],
      dtype=object)

In [ ]:
df2.describe()

A                    B    C    D
count  4.0                    4  4.0  4.0
mean   1.0  2025-07-26 00:00:00  1.0  3.0
min    1.0  2025-07-26 00:00:00  1.0  3.0
25%    1.0  2025-07-26 00:00:00  1.0  3.0
50%    1.0  2025-07-26 00:00:00  1.0  3.0
75%    1.0  2025-07-26 00:00:00  1.0  3.0
max    1.0  2025-07-26 00:00:00  1.0  3.0
std    0.0                  NaN  0.0  0.0

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving Finance_Csv.csv to Finance_Csv.csv


In [ ]:
list(uploaded.keys())

['Finance_Csv.csv']

In [ ]:
df = pd.read_csv("Finance_Csv.csv")

In [ ]:
df.describe()

Sep-20   ? 2,000.00
count      229          231
unique     124          153
top     11-Jan  ? 50,000.00
freq         7           12

In [ ]:
df.head()

Sep-20    ? 2,000.00
0  Sep-21   ? 50,000.00
1  Sep-26  ? 550,000.00
2  Sep-30  ? 100,000.00
3   4-Oct  ? 550,000.00
4  20-Oct  ? 250,000.00

In [ ]:
df.columns

Index(['Sep-20', '? 2,000.00'], dtype='object')

In [ ]:
df.dtypes

Sep-20        object
? 2,000.00    object
dtype: object

In [ ]:
uploaded = files.upload()

Saving Finance_Csv.csv to Finance_Csv (1).csv


In [ ]:
df = pd.read_csv("Finance_Csv (1).csv")

In [ ]:
df.head()

20-Sep    2,000.00
0  21-Sep   50,000.00
1  26-Sep  550,000.00
2  30-Sep  100,000.00
3   4-Oct  550,000.00
4  20-Oct  250,000.00

In [ ]:
df.describe()

20-Sep   2,000.00
count      229        231
unique     124        153
top     11-Jan  50,000.00
freq         7         12

In [ ]:
uploaded = files.upload()

Saving Finance_Csv.csv to Finance_Csv (2).csv


In [ ]:
df = pd.read_csv("Finance_Csv (2).csv")

In [ ]:
df.describe

<bound method NDFrame.describe of        Date      Amount
0    20-Sep    2,000.00
1    21-Sep   50,000.00
2    26-Sep  550,000.00
3    30-Sep  100,000.00
4     4-Oct  550,000.00
..      ...         ...
247   6-Jul    9,500.00
248   7-Jul         890
249  11-Jul         500
250  11-Jul   10,000.00
251  12-Jul   26,200.00

[252 rows x 2 columns]>

In [ ]:
df.describe()

Date     Amount
count      230        232
unique     125        153
top     11-Jan  50,000.00
freq         7         12

In [ ]:
df.dtypes

Date      object
Amount    object
dtype: object

In [ ]:
import os

In [ ]:
if os.path.exists("Finance_Csv.csv"):
  os.remove("Finance_Csv.csv")

In [ ]:
uploaded = files.upload()

Saving Finance_Csv.csv to Finance_Csv.csv


In [ ]:
from torch.utils.data import Dataset
import pandas as pd
import torchvision
from torchvision.io import decode_image

class CustomDataset(Dataset):
  def __init__(self, annotations_file, img_dir, transforms=None, target_transforms=None):
    self.img_labels = pd.read_csv(annotations_file)
    self.img_dir = img_dir
    self.transforms = transforms
    self.target_transforms = target_transforms

  def __len__(self):
    return len(list(self.img_labels.iloc[0]))

  def __get_item__(self, idx):
    img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
    image = decode_image(img_path)
    label = self.img_labels.iloc[idx]
    if self.transform:
      image = self.transform(image)
    if self.target_transform:
      label = self.target_transform(label)
    return image, label




In [ ]:
from torch.utils.data import DataLoader

train_loader = DataLoader(training_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=True)

In [ ]:
train_features, train_labels = next(iter(train_loader))
print(f"Feature batch shape : {train_features.shape()}")
print(f"Labels batch size : {train_labels.shape()}")
training_image = train_features[0].squeeze
plt.imshow(training_image, cmap="grey")
plt.show
print(f"Label: {train_labels[0]}")