<a href="https://colab.research.google.com/github/JaganMurugan/Learning/blob/main/PyTorch/Pytorch_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
x_ones = torch.ones_like(x_data)

In [4]:
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)

In [6]:
print(f"Rand Tensor \n {x_rand} \n")

Rand Tensor 
 tensor([[0.8564, 0.6247],
        [0.7888, 0.6827]]) 



In [7]:
shape = (2,3)

In [11]:
rand_tensor = torch.rand(shape)

In [13]:
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [14]:
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Zero Tensor: \n {zeros_tensor} \n")

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Random Tensor: 
 tensor([[0.6351, 0.4895, 0.0563],
        [0.0915, 0.1690, 0.0699]]) 

Zero Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [15]:
print(f"Shape: \n {x_rand.shape} \n DataType: \n {x_rand.dtype} \n Device: \n {x_rand.device} \n")

Shape: 
 torch.Size([2, 2]) 
 DataType: 
 torch.float32 
 Device: 
 cpu 



In [8]:
torch.cuda.is_available()

True

In [9]:
if torch.cuda.is_available():
  x_data.to("cuda")

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8]])